baseURL='https://www.basketball-reference.com/'
nhlBaseURL='https://www.hockey-reference.com/'
mlbBaseURL='https://www.baseball-reference.com/'
mlbWebSiteBaseURL='https://www.mlb.com/'
nbaBaseURL='https://www.nba.com/'
connectionStringNBA='mysql+pymysql://sa:RomuloJalim70@localhost:3306/nbaonnumbers'
connectionStringNHL='mysql+pymysql://sa:RomuloJalim70@localhost:3306/nbaonnumbers'